### PR TITLE
add amalgamation build

### PR DESCRIPTION
**Pull request by ghost**
+\+ tested only on GNU/Linux

### CODE REVIEW

**Comment by faelys** [comment]
As it currently is, the script does not work  in operating systems whose `sed` doesn't have an argumentless variant of `-i`, which is the case at least for my FreeBSD. I would suggest moving the whitespace fix into `outputsource` function.

Also I would prefer to have a licence header in the script too.

Otherwise the script is indeed simple and clear to adopt responsibility for it, even though I would have done.

Do you prefer to make a new pull request with those changes, or to leave me accept this pull request and do the changes myself? I don't mind either way.

**Comment by ghost** [comment]
Should I rebase it ?

**Comment by faelys** [comment]
As you prefer, I don't mind it either way

**Comment by ghost** [comment]
then I leave it as is

**Comment by faelys** [comment]
Ok, thanks a lot for your contribution!

**Pull request merged**
