### PR TITLE
soldout_*.3: put in the section NAME all functions names

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
I've also added into `soldout_markdown.3`
`.Nm soldout_markdown` for consistency, not sure if it is ok..

.. or would it be better if the manual pages could be without `soldout` namespace..?

| current fname | new fname |
| --- | --- |
| soldout_array | arr_init |
| soldout_buffer | bufnew |
| soldout_markdown | markdown |
| soldout_renderers | ??? |

**Comment by ghost** [comment]
BTW, what does **lus** mean in functions `lus_attr_escape()` and `lus_body_escape()` ?

**Comment by chybz** [comment]
I personally prefer functions to have a namespace as I find it easier to locate documentation in a project using multiple libraries.
Regarding **lus**, those functions may have been copied from [libupskirt](https://github.com/siuying/libupskirt)...

**Comment by faelys** [comment]
I would tend to favor namespaces by default too. This is a project too small to risk cluttering a root namespace, so I would rather stay in a dedicated namespace unless it's idiomatic not to do so.

**lus** indeed stands for `libupskirt`, but actually siuying/libupskirt was the one to copy (or rather fork) the code, back before the sh*tstorm that led to the project being renamed as it is today and my leaving of the open-source world (which turned out to be temporary, for only a few years). 

The function names have not updated to the logical **lso** prefix because the codebase already in maintenance mode.

**Comment by ghost** [comment]
I was asking about a namespace for the **manual pages** file names.

if the functions do not have a namespace, then should the same  be for the manual pages ?

But I don't know what name could be for the `soldout_renderers.3`..

**Comment by faelys** [comment]
I did understand it as manpage namespace, which is system-wide, while function namespace only extend inside a single executable. So I feel less justified in claiming general names in the former than in the latter.

**Pull request merged**
