### PR TITLE
manual pages cleanup

### PR DESCRIPTION
**Pull request by ghost**
They are far from perfection.
So, I'm going to rewrite them a bit.

### CODE REVIEW

**Comment by ghost** [comment]
++
how about to add to the makefiles rule that checks manual pages?
in my projects, i have something like this:

```
www/manpage.1.html: manpage.1
  mandoc -Thtml -Wall,stop -Ostyle=man.css manpage.1 > $@
html: www/manpage.1.html
```

for now it could be just this:

```
mancheck:
  mandoc -Tlint *.1 *.3
```

**Comment by faelys** [comment]
> how about to add to the makefiles rule that checks manual pages?

I'm OK with that, and even with the HTML generation target, which would help with #25 assuming the new targets are not build by default (so that there is no hard dependency to mandoc).

Would you like a bit more time to gather more commits here, or should I review and merge them as soon as I have the opportunity?

**Comment by ghost** [comment]
Where do you plan to host them (fossil / github) ?

should I add `man.css` into `www` (or [docs](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch) or whatever) subdir?
or could you host `man.css` on your webserver?

**Comment by ghost** [comment]
I hope they're a bit better now and you can do a review.

**Comment by faelys** [comment]
I don't disagree with anything in these changes, but I admit trusting you for the most part.

**Pull request merged**
