### PR TITLE
Add install and uninstall targets to GNUmakefile

### PR DESCRIPTION
**Pull request by craigbarnes**
Hi. This adds `install` and `uninstall` targets to the GNUmakefile. I think it should be portable to *BSD or any POSIX system too but I didn't touch BSDmakefile, since I have no way to test.

### CODE REVIEW

**Comment by faelys** [comment]
I originally didn't provide an install target because not only it is OS specific, but it tends to be also distribution specific, so I felt it's a job better suited for a maintener.

For example, I see you keep default user and group, while on my computers system-wide files tend to be owned by root:wheel. On the other hand, a non-maintainer install (as is the kind a makefile in this projet would provide) is more likely to be performed by an unpriviliged user, so we can't force that either.

Also I don't see any call to ldconfig, is it optional on your distribution?

All in all I'm still unconvinced a proper install can be performed in a distribution-agnostic way.

**Comment by faelys** [comment]
Oh and do you really need to set execute permissions on the library shared object file?

**Comment by craigbarnes** [comment]
> For example, I see you keep default user and group, while on my computers system-wide files tend to be owned by root:wheel. On the other hand, a non-maintainer install (as is the kind a makefile in this projet would provide) is more likely to be performed by an unpriviliged user, so we can't force that either.

Fair point. Using an `INSTALL` variable would allow this to be overridden, e.g.:

```
make install INSTALL='install -o root -g wheel -m 0755'
```

> Also I don't see any call to ldconfig, is it optional on your distribution?

It's not optional, but for packaging purposes it's not run at the same time as `make install`.

> do you really need to set execute permissions on the library shared object file?

On Fedora I do, yes.

**Comment by craigbarnes** [comment]
Actually, the more I think about it the more it seems easier to just do it manually per-distro.

**Pull request closed without merging**
