### PR TITLE
adjust makefiles

### PR DESCRIPTION
**Pull request by ghost**
- add configurable CC, CFLAGS and LDFLAGS
- remove useless flags for LDFLAGS
- add a static library build

### CODE REVIEW

**Comment by ghost** [comment]
How about to link `mkd2html`, `mkd2latex`, `mkd2man` and `benchmark` against  a static library ?

**Comment by faelys** [comment]
I accept the pull, but I still wonder, are you sure that the flags in LDFLAGS are useless?

I thought that LTO was starting to be a thing, and the documentation of my `ld` says `-O` is recognized without saying it has no effect (unlike `-g`). Especially with some functions in `array.c` and `buffer.c` that very easy candidates for LTO.

I also thought that the `-W…` options were useful, I think I remember having added the whole `LDFLAGS` thing to the makefile when I had a link-time warning I wish was fatal. But that was many years ago, maybe I'm misremembering, since I can't find any hint in my documentation about `ld` using these flags (even though it has some warning-related flags, just not in `-W`).

As far as statically linking the tools, that would probably make testing easier, not having to deal with `LD_LIBRARY_PATH` to use current code instead of installed library. But on the other hand, some distributions seem to actually provides them as utilities (probably not `benchmark`, that would make no sense, but the `mkd2*` family could have direct users) and usually prefer shipping dynamically-linked libraries.

At the moment I don't really lean towards one side or the other, I guess a case could be made for providing both dynamic and static build recipes, but then the question still remains on which one to use by default.

**Comment by ghost** [comment]
Oops.., I didn't know about it;
then default `LDFLAGS` could be just `-O3`..

**Comment by ghost** [comment]
..or just put `-O3` alongside of `$(LDFLAGS)`.

**Comment by ghost** [comment]
++
I forgot  to add `*.a` into `.gitignore`...

**Pull request merged**
